### PR TITLE
Create password protected zip archive.

### PR DESCRIPTION
**Pull request by bokic**
Extend the library so it can create password protected zip archives.

### CODE REVIEW

**Comment by scspijker** [comment]
This is a nice addition!

One question, since the password guarded zip is created with Zip64 (Extended Information), can the current unzipping functions unzip this zipfile again?

If yes, I would vote for an immediate pull/merge :+1:

**Comment by istx25** [comment]
@bokic Would you be able to answer @scspijker's question?

**Comment by bokic** [comment]
It should.

If you look at the implementation of zipOpenNewFileInZip(or later variant),
then you will see that it only calls zipOpenNewFileInZip4_64, with 0 as
zip64 parameter. Thus it doesn't matter if we call zip64 directly.

Here is the implementation :

extern int ZEXPORT zipOpenNewFileInZip (zipFile file, const char* filename,
const zip_fileinfo* zipfi,

                                        const void* extrafield_local, uInt
size_extrafield_local,

                                        const void*extrafield_global, uInt
size_extrafield_global,

                                        const char* comment, int method, int
level)

{

    return zipOpenNewFileInZip4_64 (file, filename, zipfi,

                                 extrafield_local, size_extrafield_local,

                                 extrafield_global, size_extrafield_global,

                                 comment, method, level, 0,

                                 -MAX_WBITS, DEF_MEM_LEVEL,
Z_DEFAULT_STRATEGY,

                                 NULL, 0, VERSIONMADEBY, 0, 0);

}


On Mon, Apr 6, 2015 at 7:22 PM, Douglas Bumby <notifications@github.com>
wrote:

> @bokic <https://github.com/bokic> Would you be able to answer @scspijker
> <https://github.com/scspijker>'s question?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soffes/ssziparchive/pull/124#issuecomment-90161817>.
>



-- 
*Boris Barbulovski*
http://mkfusion.bokicsoft.com/

**Comment by istx25** [comment]
Thanks @bokic for answering back! Would you be able to create a new pull request with the desired changes on-top of the latest codebase?

**Comment by bokic** [comment]
Sure.

**Comment by scspijker** [comment]
@bokic Another user requested this change, would you still be interested in creating the pull request? :)

**Pull request closed without merging**
